server.port=${SERVER_PORT:8083}

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/partydb}
spring.datasource.username=${DB_USER:banquito}
spring.datasource.password=${DB_PASS:banquito123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

party.grpc.port=${PARTY_GRPC_PORT:9093}
account-core.grpc.host=${ACCOUNT_CORE_GRPC_HOST:localhost}
account-core.grpc.port=${ACCOUNT_CORE_GRPC_PORT:9091}